### ISSUE TITLE
cd'ing to /ram has strange error codes blasted into the screen

### ISSUE THREAD

**Issue by xandark** [A2osX/A2osX#153]
This is with the latest Stable Release build 2124, which by the way is freaking cool! 

When I do 

`cd /ram`

...on the 7th line of the screen, I'm seeing 

```F E 0 0 0 A    0 0    A 4 0 0```

blasted into the screen, instead of output through the console. Some kind of kernel error? It turns out that `cd /anything` has the same effect. I also notice on boot that in the same part of the screen when the logo is loaded, there appears to be a similar pattern, albeit on the GR screen. Something similar?

**Comment by patrickbst** [comment]
@xandark The 2124 build includes some debug code related to the new XRW code that has been added to ProDOS FX.  This code shows when accessing floppy drives.  Since your command (CD) is attempting to change the directory to a volume, ProDOS has to first look at all online drives (including Floppies) to see if the volume you want (in this case /RAM) is online.  This makes it access any floppy drives in your system, hence you get the debug output as it hits those drives.  This is normal for this particular build.  It will be removed in future releases.

**Comment by xandark** [comment]
okay, very good
